version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5
    target-branch: main
    commit-message:
      prefix: 'bump'
      include: 'scope'
    groups:
      production-dependencies:
        dependency-type: 'production'
      dev-dependencies:
        dependency-type: 'development'

  # Github actions up to date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5
    target-branch: main
    commit-message:
      prefix: 'bump'
      include: 'scope'
