packages:
  - packages/@repo/*
  - packages/cli

allowBuilds:
  esbuild: false

# The minimum age of a release before it can be automatically updated by pnpm.
minimumReleaseAge: 1440 # 1 day in minutes
